const paragraphs = [
    "The sun set behind the mountains, filling the sky with soft shades of orange, pink, and fading gold. The light slowly disappeared, creating a calm and peaceful atmosphere that made everything feel still. Birds returned to their nests while a gentle breeze moved quietly across the land. It was one of those rare moments where time seemed to slow down, allowing everything to exist in perfect balance. The mountains stood silently as the sky changed colors, creating a beautiful scene that required no effort to enjoy. As darkness approached, a sense of calm settled in, reminding anyone watching that nature’s beauty is simple, quiet, and always present for those who pause and notice it.",

    "Learning to code is like learning a completely new language that requires logic, patience, and consistent effort. At first, it may feel confusing with unfamiliar symbols and errors that seem difficult to understand. However, with practice, things begin to make sense, and small successes start building confidence. Coding is not just about writing instructions for computers; it is about solving problems and creating meaningful solutions. Each challenge helps improve thinking skills and creativity. Over time, the process becomes more enjoyable and rewarding. As understanding grows, so does the ability to build applications and bring ideas to life. Eventually, coding opens doors to endless opportunities, allowing individuals to create, innovate, and shape the digital world around them.",

    "She walked through the busy city streets, surrounded by noise and constant movement, yet she felt completely lost in her thoughts. Cars passed by, people hurried along, and conversations blended into the background. Despite all this activity, her mind was focused elsewhere, far from the chaos around her. Each step felt automatic, as if she was moving without thinking. The city lights reflected around her, but she barely noticed them. It was strange to feel alone in such a crowded place, yet there was also comfort in that quiet space within her mind. As she continued walking, the outside world slowly faded, leaving only her thoughts and the steady rhythm of her footsteps guiding her forward.",

    "With a cup of coffee in his hand, he sat by the window watching the rain fall steadily. The droplets tapped softly against the glass, creating a peaceful rhythm that filled the room. Outside, the streets looked quiet and reflective under the gray sky, while people hurried by with umbrellas. Inside, everything felt calm and warm. The contrast between the cold rain and the warmth of his drink created a comforting feeling. He took a slow sip, letting his thoughts wander freely. There was something relaxing about watching the rain, something that made worries feel smaller. In that moment, nothing else mattered. It was simply a quiet space, filled with calm, warmth, and stillness.",

    "The old library smelled of aged paper and quiet history, creating a peaceful and thoughtful environment. Tall shelves filled with books stretched across the room, each holding stories waiting to be discovered. The silence was not empty but meaningful, filled with the soft sound of pages turning. Light entered gently through windows, adding to the calm atmosphere. Every book represented knowledge, imagination, and experience from different times and places. Visitors moved quietly, respecting the space and its purpose. It felt like a place where time slowed down, allowing people to focus and explore. The library was more than just a building; it was a world of ideas, offering endless opportunities to learn, think, and discover new perspectives.",

    "Success is not a final destination but a continuous journey filled with effort and learning. Failure is not the end but a step that teaches important lessons. What matters most is the courage to keep going, even when things become difficult. Every small step contributes to progress and growth. Challenges help build strength and reveal hidden potential. It is important to stay patient and focused, understanding that success takes time. There will be moments of doubt, but persistence makes the difference. By learning from mistakes and continuing forward, it becomes possible to achieve meaningful goals. In the end, success is not defined by one moment but by the journey, effort, and determination shown along the way.",

    "He pressed the keys gently, bringing his thoughts to life on the screen. Writing was his way of understanding the world and expressing emotions. The sound of typing created a rhythm that helped him focus. Sometimes words came easily, while other times they required effort and patience. Even during struggles, the process remained meaningful. Writing allowed him to explore ideas, imagine possibilities, and create something unique. It gave him a space to be honest and creative without limits. As the page filled with words, a sense of accomplishment grew. Each sentence added clarity to his thoughts. In that moment, writing was not just an activity but a powerful way to connect ideas and express understanding.",

    "The ocean waves moved steadily toward the shore, creating a calming and natural rhythm. The sound of water meeting sand was both powerful and peaceful. Seagulls flew overhead, their calls blending with the breeze. The horizon stretched far into the distance, where the sky met the sea. The sand shifted underfoot, warm yet soft. Watching the waves felt relaxing, as if each movement carried away stress. People walked quietly along the beach, enjoying the moment. The ocean had a way of making everything feel smaller and simpler. Standing there, surrounded by nature, it was easy to forget worries and focus on the present. It was a peaceful reminder of nature’s beauty and balance.",

    "In a world full of changing trends, staying true to oneself is important. Being authentic means understanding personal values and not losing identity in the process of fitting in. Trends may come and go, but individuality remains meaningful. It takes confidence to follow one’s own path, especially when it differs from others. However, authenticity leads to deeper satisfaction and stronger connections. It allows people to grow honestly and build a life that reflects their true interests. Instead of chasing what is popular, focusing on personal goals creates a stronger sense of purpose. In the end, being genuine is more valuable than temporary approval. Staying true to oneself brings lasting confidence and meaningful direction in life.",

    "The first step to solving any problem is recognizing that it exists. Without awareness, problems can grow and become more difficult to handle. Once identified, it becomes easier to understand the situation clearly. Awareness helps in finding the root cause rather than just the surface issue. Ignoring problems may feel easier, but it leads to bigger challenges later. Facing them creates opportunities to learn and improve. It encourages thinking, planning, and taking action. Every problem carries a lesson that can help in personal growth. By staying calm and focused, solutions become clearer. In the end, recognizing and addressing problems leads to progress and better outcomes in both personal and professional life.",

    "She smiled at a stranger while passing by, a small gesture that carried unexpected meaning. The stranger returned the smile, creating a brief but genuine connection. In a busy world, such simple acts of kindness can make a difference. It showed that kindness does not require effort or planning. Even small actions can brighten someone’s day. That moment had the potential to influence mood and spread positivity. The stranger might carry that feeling forward and share it with others. These small interactions remind people of human connection. Kindness creates a ripple effect that goes beyond the moment. In the end, simple gestures often leave the strongest impact and make everyday life a little better.",

    "The clock ticked loudly in the silent room, marking each passing second clearly. The sound became more noticeable as everything else remained still. It served as a reminder that time continues no matter what. Sitting there, he realized how quickly moments pass. The silence felt heavy, filled only by the steady ticking. It created both awareness and pressure to use time wisely. At the same time, the consistency of the clock felt calming. It moved at its own pace, unaffected by anything else. That moment brought clarity about the importance of time. Every second mattered, whether used or wasted. It was a simple but powerful reminder to value time and make the most of it."
];